export enum EventStatus {
    SCHEDULED = "SCHEDULED",
    REGISTRATION_OPEN = "REGISTRATION_OPEN",
    REGISTRATION_CLOSED = "REGISTRATION_CLOSED",
    COMPLETED = "COMPLETED",
    CANCELLED = "CANCELLED",
}